// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3QA26qrdwXjt1eRn_OBqX0zw8kbiyV3o',
    appId: '1:348602182315:web:e5b92040815a2ef94665ee',
    messagingSenderId: '348602182315',
    projectId: 'rd-final',
    authDomain: 'rd-final.firebaseapp.com',
    databaseURL: 'https://rd-final-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rd-final.firebasestorage.app',
    measurementId: 'G-WBN9RY3QKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5faRhRRuQ_k1NwbqFpPwtVpc1VD1JXaI',
    appId: '1:348602182315:android:f2bc9c87addef5b84665ee',
    messagingSenderId: '348602182315',
    projectId: 'rd-final',
    databaseURL: 'https://rd-final-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rd-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcOgwwLzoQqIu5MmQuELDtp_btz7JMo3I',
    appId: '1:348602182315:ios:f2d73785bd0f81144665ee',
    messagingSenderId: '348602182315',
    projectId: 'rd-final',
    databaseURL: 'https://rd-final-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rd-final.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcOgwwLzoQqIu5MmQuELDtp_btz7JMo3I',
    appId: '1:348602182315:ios:f2d73785bd0f81144665ee',
    messagingSenderId: '348602182315',
    projectId: 'rd-final',
    databaseURL: 'https://rd-final-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rd-final.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3QA26qrdwXjt1eRn_OBqX0zw8kbiyV3o',
    appId: '1:348602182315:web:6e1d021b8661ad474665ee',
    messagingSenderId: '348602182315',
    projectId: 'rd-final',
    authDomain: 'rd-final.firebaseapp.com',
    databaseURL: 'https://rd-final-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rd-final.firebasestorage.app',
    measurementId: 'G-SM6FCCPHMW',
  );

}